import '../styles/globals.css'
import { EnglishProvider } from '../context/englishContext'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <EnglishProvider >
      <Head>
        <title>Alfredo Blanco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AB.ico" />
      </Head>
      <Component {...pageProps} />
    </EnglishProvider>
  )
}

export default MyApp
