import type { NextPage } from 'next'
import Head from 'next/head'
import Present from '../Components/Present';
import Technologies from '../Components/Tech';
import Projects from '../Components/Projects';
import Contact from '../Components/Contact';
import NavBar from '../Components/Navbar';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.all}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Present />
      <NavBar />
      <Technologies />
      <Projects />
      <Contact />
    </div>
  )
}

export default Home
